#!/bin/bash
# by Greg Lawler greg@outsideopen.com
#

if [[ -r "/etc/default/pfmb" ]] ; then
  source /etc/default/pfmb
fi

##### Configuration settings - See README for details
: ${config:=hosts.conf}
: ${backupuser:=backup}
: ${backupdir:=backups}
: ${backupcopies:=25}

##### Other settings - don't change these willy-nilly unless you know what you're doing! #####
datestamp=$(date '+%Y-%m-%d-%s')

# Path on pfSense to the XML configuration file.
: ${xmlpath:=/cf/conf/config.xml}

function isint() {
  re='^[0-9]+$'
  if ! [[ $1 =~ $re ]] ; then
    echo "Error: $1 is not a valid port number.  Check your $config syntax..." >&2; exit 1
  fi
}

function rotateBackups() {
  OLDIFS=$IFS
  IFS=$'\n'
  files=$(find "$backupdir/$name" -name "$name-$host-*.xml" | sort | tail -n $backupcopies)
  find "$backupdir/$name" -name "$name-$host-*.xml" | while read i; do
    keep=0
    for a in ${files[@]}; do
      if [ "$i" == "$a" ]; then
        keep=1;
      fi
    done
    if [ $keep == 0 ]; then
      rm "$i"
    fi
  done
  IFS=$OLDIFS
}

function main() {
  while IFS=':' read -r host port desc; do
    if [ -n "$port" ] ; then
      isint $port
    else
      port=22
    fi

    # setup vars for use
    name=${desc:-$host}
    backup_file="$backupdir/$name/$name-$host-$datestamp.xml"

    # create dir if doesn't exist
    if ! [[ -d "$backupdir/$name" && ! -L "$backupdir/$name" ]] ; then
      mkdir -p $backupdir/$name
    fi

    #run the backups
    case $host in
      *@*)
        ;;
      *)
        host="$backupuser@$host"
        ;;
    esac
    scp -q -P $port $host:$xmlpath "${backup_file}"
    if [ $? -eq 0 ] && [ -s "${backup_file}" ]; then
      echo "Backing up $name... OK"
      rotateBackups
    else
      echo "Backing up $name... FAILED"
    fi
  done < $config
}
main
